#pragma once

// =============================================================================
// Aspose.PDF FOSS for C++ — single entry point.
//
// Includes every public header under <aspose/pdf/...>, so client code can
// simply write:
//
//     #include <aspose.pdf.foss.hpp>
//
// Individual headers remain available for finer-grained includes.
// =============================================================================

#include <aspose/pdf/af_relationship.hpp>
#include <aspose/pdf/artifact.hpp>
#include <aspose/pdf/artifact_collection.hpp>
#include <aspose/pdf/base_paragraph.hpp>
#include <aspose/pdf/bitmap_info.hpp>
#include <aspose/pdf/bmp_device.hpp>
#include <aspose/pdf/border_info.hpp>
#include <aspose/pdf/border_side.hpp>
#include <aspose/pdf/cell.hpp>
#include <aspose/pdf/cells.hpp>
#include <aspose/pdf/color.hpp>
#include <aspose/pdf/color_depth.hpp>
#include <aspose/pdf/compression_type.hpp>
#include <aspose/pdf/crypto_algorithm.hpp>
#include <aspose/pdf/device.hpp>
#include <aspose/pdf/document.hpp>
#include <aspose/pdf/document_device.hpp>
#include <aspose/pdf/document_info.hpp>
#include <aspose/pdf/document_privilege.hpp>
#include <aspose/pdf/embedded_file_collection.hpp>
#include <aspose/pdf/encoding.hpp>
#include <aspose/pdf/file_encoding.hpp>
#include <aspose/pdf/file_specification.hpp>
#include <aspose/pdf/floating_box.hpp>
#include <aspose/pdf/font.hpp>
#include <aspose/pdf/font_repository.hpp>
#include <aspose/pdf/form_presentation_mode.hpp>
#include <aspose/pdf/graph_info.hpp>
#include <aspose/pdf/horizontal_alignment.hpp>
#include <aspose/pdf/hyperlink.hpp>
#include <aspose/pdf/i_index_bitmap_converter.hpp>
#include <aspose/pdf/image_device.hpp>
#include <aspose/pdf/jpeg_device.hpp>
#include <aspose/pdf/load_options.hpp>
#include <aspose/pdf/margin_info.hpp>
#include <aspose/pdf/margins.hpp>
#include <aspose/pdf/metadata.hpp>
#include <aspose/pdf/named_destination_collection.hpp>
#include <aspose/pdf/numbering_style.hpp>
#include <aspose/pdf/outline_collection.hpp>
#include <aspose/pdf/outline_item_collection.hpp>
#include <aspose/pdf/outlines.hpp>
#include <aspose/pdf/page.hpp>
#include <aspose/pdf/page_collection.hpp>
#include <aspose/pdf/page_coordinate_type.hpp>
#include <aspose/pdf/page_device.hpp>
#include <aspose/pdf/page_label.hpp>
#include <aspose/pdf/page_label_collection.hpp>
#include <aspose/pdf/page_size.hpp>
#include <aspose/pdf/paragraphs.hpp>
#include <aspose/pdf/password_type.hpp>
#include <aspose/pdf/pdf_format.hpp>
#include <aspose/pdf/permissions.hpp>
#include <aspose/pdf/png_device.hpp>
#include <aspose/pdf/point.hpp>
#include <aspose/pdf/position.hpp>
#include <aspose/pdf/rectangle.hpp>
#include <aspose/pdf/rendering_options.hpp>
#include <aspose/pdf/resolution.hpp>
#include <aspose/pdf/resources.hpp>
#include <aspose/pdf/rotation.hpp>
#include <aspose/pdf/row.hpp>
#include <aspose/pdf/rows.hpp>
#include <aspose/pdf/shape_type.hpp>
#include <aspose/pdf/svg_load_options.hpp>
#include <aspose/pdf/table.hpp>
#include <aspose/pdf/text_absorber.hpp>
#include <aspose/pdf/text_builder.hpp>
#include <aspose/pdf/text_device.hpp>
#include <aspose/pdf/text_fragment.hpp>
#include <aspose/pdf/text_fragment_absorber.hpp>
#include <aspose/pdf/text_fragment_collection.hpp>
#include <aspose/pdf/text_fragment_state.hpp>
#include <aspose/pdf/text_paragraph.hpp>
#include <aspose/pdf/text_state.hpp>
#include <aspose/pdf/tiff_device.hpp>
#include <aspose/pdf/tiff_settings.hpp>
#include <aspose/pdf/vertical_alignment.hpp>
#include <aspose/pdf/watermark_artifact.hpp>
#include <aspose/pdf/x_image.hpp>
#include <aspose/pdf/x_image_collection.hpp>
#include <aspose/pdf/xmp_value.hpp>

// annotations
#include <aspose/pdf/annotations/annotation.hpp>
#include <aspose/pdf/annotations/annotation_collection.hpp>
#include <aspose/pdf/annotations/annotation_flags.hpp>
#include <aspose/pdf/annotations/annotation_selector.hpp>
#include <aspose/pdf/annotations/annotation_state.hpp>
#include <aspose/pdf/annotations/annotation_state_model.hpp>
#include <aspose/pdf/annotations/annotation_type.hpp>
#include <aspose/pdf/annotations/bleed_mark_annotation.hpp>
#include <aspose/pdf/annotations/border.hpp>
#include <aspose/pdf/annotations/border_effect.hpp>
#include <aspose/pdf/annotations/border_style.hpp>
#include <aspose/pdf/annotations/cap_style.hpp>
#include <aspose/pdf/annotations/caption_position.hpp>
#include <aspose/pdf/annotations/caret_annotation.hpp>
#include <aspose/pdf/annotations/caret_symbol.hpp>
#include <aspose/pdf/annotations/characteristics.hpp>
#include <aspose/pdf/annotations/circle_annotation.hpp>
#include <aspose/pdf/annotations/color_bar_annotation.hpp>
#include <aspose/pdf/annotations/colors_of_cmyk.hpp>
#include <aspose/pdf/annotations/common_figure_annotation.hpp>
#include <aspose/pdf/annotations/corner_printer_mark_annotation.hpp>
#include <aspose/pdf/annotations/default_appearance.hpp>
#include <aspose/pdf/annotations/explicit_destination.hpp>
#include <aspose/pdf/annotations/explicit_destination_type.hpp>
#include <aspose/pdf/annotations/file_attachment_annotation.hpp>
#include <aspose/pdf/annotations/file_icon.hpp>
#include <aspose/pdf/annotations/fit_b_explicit_destination.hpp>
#include <aspose/pdf/annotations/fit_bh_explicit_destination.hpp>
#include <aspose/pdf/annotations/fit_bv_explicit_destination.hpp>
#include <aspose/pdf/annotations/fit_explicit_destination.hpp>
#include <aspose/pdf/annotations/fit_h_explicit_destination.hpp>
#include <aspose/pdf/annotations/fit_r_explicit_destination.hpp>
#include <aspose/pdf/annotations/fit_v_explicit_destination.hpp>
#include <aspose/pdf/annotations/free_text_annotation.hpp>
#include <aspose/pdf/annotations/free_text_intent.hpp>
#include <aspose/pdf/annotations/go_to_action.hpp>
#include <aspose/pdf/annotations/go_to_uri_action.hpp>
#include <aspose/pdf/annotations/highlight_annotation.hpp>
#include <aspose/pdf/annotations/highlighting_mode.hpp>
#include <aspose/pdf/annotations/i_appointment.hpp>
#include <aspose/pdf/annotations/ink_annotation.hpp>
#include <aspose/pdf/annotations/javascript_action.hpp>
#include <aspose/pdf/annotations/justification.hpp>
#include <aspose/pdf/annotations/line_annotation.hpp>
#include <aspose/pdf/annotations/line_ending.hpp>
#include <aspose/pdf/annotations/line_intent.hpp>
#include <aspose/pdf/annotations/link_annotation.hpp>
#include <aspose/pdf/annotations/markup_annotation.hpp>
#include <aspose/pdf/annotations/movie_annotation.hpp>
#include <aspose/pdf/annotations/named_action.hpp>
#include <aspose/pdf/annotations/named_destination.hpp>
#include <aspose/pdf/annotations/page_information_annotation.hpp>
#include <aspose/pdf/annotations/pdf_action.hpp>
#include <aspose/pdf/annotations/poly_annotation.hpp>
#include <aspose/pdf/annotations/poly_intent.hpp>
#include <aspose/pdf/annotations/polygon_annotation.hpp>
#include <aspose/pdf/annotations/polyline_annotation.hpp>
#include <aspose/pdf/annotations/popup_annotation.hpp>
#include <aspose/pdf/annotations/predefined_action.hpp>
#include <aspose/pdf/annotations/printer_mark_annotation.hpp>
#include <aspose/pdf/annotations/printer_mark_corner_position.hpp>
#include <aspose/pdf/annotations/printer_mark_side_position.hpp>
#include <aspose/pdf/annotations/printer_marks_kind.hpp>
#include <aspose/pdf/annotations/redaction_annotation.hpp>
#include <aspose/pdf/annotations/registration_mark_annotation.hpp>
#include <aspose/pdf/annotations/reply_type.hpp>
#include <aspose/pdf/annotations/rich_media_annotation.hpp>
#include <aspose/pdf/annotations/rich_text_font_styles.hpp>
#include <aspose/pdf/annotations/screen_annotation.hpp>
#include <aspose/pdf/annotations/sound_annotation.hpp>
#include <aspose/pdf/annotations/sound_icon.hpp>
#include <aspose/pdf/annotations/square_annotation.hpp>
#include <aspose/pdf/annotations/squiggly_annotation.hpp>
#include <aspose/pdf/annotations/stamp_annotation.hpp>
#include <aspose/pdf/annotations/stamp_icon.hpp>
#include <aspose/pdf/annotations/strike_out_annotation.hpp>
#include <aspose/pdf/annotations/submit_form_action.hpp>
#include <aspose/pdf/annotations/text_alignment.hpp>
#include <aspose/pdf/annotations/text_annotation.hpp>
#include <aspose/pdf/annotations/text_icon.hpp>
#include <aspose/pdf/annotations/text_markup_annotation.hpp>
#include <aspose/pdf/annotations/text_style.hpp>
#include <aspose/pdf/annotations/trim_mark_annotation.hpp>
#include <aspose/pdf/annotations/underline_annotation.hpp>
#include <aspose/pdf/annotations/watermark_annotation.hpp>
#include <aspose/pdf/annotations/widget_annotation.hpp>
#include <aspose/pdf/annotations/xyz_explicit_destination.hpp>

// drawing
#include <aspose/pdf/drawing/circle.hpp>
#include <aspose/pdf/drawing/ellipse.hpp>
#include <aspose/pdf/drawing/graph.hpp>
#include <aspose/pdf/drawing/line.hpp>
#include <aspose/pdf/drawing/rectangle.hpp>
#include <aspose/pdf/drawing/shape.hpp>

// facades
#include <aspose/pdf/facades/algorithm.hpp>
#include <aspose/pdf/facades/alignment_type.hpp>
#include <aspose/pdf/facades/auto_rotate_mode.hpp>
#include <aspose/pdf/facades/blending_color_space.hpp>
#include <aspose/pdf/facades/bookmark.hpp>
#include <aspose/pdf/facades/bookmarks.hpp>
#include <aspose/pdf/facades/data_type.hpp>
#include <aspose/pdf/facades/default_metadata_properties.hpp>
#include <aspose/pdf/facades/encoding_type.hpp>
#include <aspose/pdf/facades/facade.hpp>
#include <aspose/pdf/facades/field_type.hpp>
#include <aspose/pdf/facades/font_style.hpp>
#include <aspose/pdf/facades/form_editor.hpp>
#include <aspose/pdf/facades/form_field_facade.hpp>
#include <aspose/pdf/facades/i_facade.hpp>
#include <aspose/pdf/facades/i_saveable_facade.hpp>
#include <aspose/pdf/facades/image_merge_mode.hpp>
#include <aspose/pdf/facades/key_size.hpp>
#include <aspose/pdf/facades/pdf_annotation_editor.hpp>
#include <aspose/pdf/facades/pdf_bookmark_editor.hpp>
#include <aspose/pdf/facades/pdf_content_editor.hpp>
#include <aspose/pdf/facades/pdf_converter.hpp>
#include <aspose/pdf/facades/pdf_extractor.hpp>
#include <aspose/pdf/facades/pdf_file_editor.hpp>
#include <aspose/pdf/facades/pdf_file_info.hpp>
#include <aspose/pdf/facades/pdf_file_security.hpp>
#include <aspose/pdf/facades/pdf_file_signature.hpp>
#include <aspose/pdf/facades/pdf_file_stamp.hpp>
#include <aspose/pdf/facades/pdf_page_editor.hpp>
#include <aspose/pdf/facades/pdf_xmp_metadata.hpp>
#include <aspose/pdf/facades/positioning_mode.hpp>
#include <aspose/pdf/facades/property_flag.hpp>
#include <aspose/pdf/facades/saveable_facade.hpp>
#include <aspose/pdf/facades/signature_name.hpp>
#include <aspose/pdf/facades/stamp_type.hpp>
#include <aspose/pdf/facades/submit_form_flag.hpp>
#include <aspose/pdf/facades/vertical_alignment_type.hpp>
#include <aspose/pdf/facades/word_wrap_mode.hpp>

// forms
#include <aspose/pdf/forms/barcode_field.hpp>
#include <aspose/pdf/forms/box_style.hpp>
#include <aspose/pdf/forms/button_field.hpp>
#include <aspose/pdf/forms/checkbox_field.hpp>
#include <aspose/pdf/forms/choice_field.hpp>
#include <aspose/pdf/forms/combo_box_field.hpp>
#include <aspose/pdf/forms/date_field.hpp>
#include <aspose/pdf/forms/doc_mdp_access_permissions.hpp>
#include <aspose/pdf/forms/doc_mdp_signature.hpp>
#include <aspose/pdf/forms/external_signature.hpp>
#include <aspose/pdf/forms/field.hpp>
#include <aspose/pdf/forms/file_select_box_field.hpp>
#include <aspose/pdf/forms/form.hpp>
#include <aspose/pdf/forms/form_type.hpp>
#include <aspose/pdf/forms/icon_caption_position.hpp>
#include <aspose/pdf/forms/icon_fit.hpp>
#include <aspose/pdf/forms/list_box_field.hpp>
#include <aspose/pdf/forms/number_field.hpp>
#include <aspose/pdf/forms/option.hpp>
#include <aspose/pdf/forms/option_collection.hpp>
#include <aspose/pdf/forms/password_box_field.hpp>
#include <aspose/pdf/forms/pkcs1.hpp>
#include <aspose/pdf/forms/pkcs7.hpp>
#include <aspose/pdf/forms/pkcs7_detached.hpp>
#include <aspose/pdf/forms/radio_button_field.hpp>
#include <aspose/pdf/forms/radio_button_option_field.hpp>
#include <aspose/pdf/forms/rich_text_box_field.hpp>
#include <aspose/pdf/forms/scaling_mode.hpp>
#include <aspose/pdf/forms/scaling_reason.hpp>
#include <aspose/pdf/forms/signature.hpp>
#include <aspose/pdf/forms/signature_custom_appearance.hpp>
#include <aspose/pdf/forms/signature_field.hpp>
#include <aspose/pdf/forms/subject_name_elements.hpp>
#include <aspose/pdf/forms/symbology.hpp>
#include <aspose/pdf/forms/text_box_field.hpp>
#include <aspose/pdf/forms/xfa.hpp>
